# Generated by Django 3.2.15 on 2022-10-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookExchange', '0002_auto_20221021_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooks',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
