# Generated by Django 4.1.2 on 2022-10-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookExchange", "0002_auto_20221021_1223"),
    ]

    operations = [
        migrations.AddField(
            model_name="textbooks",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
