# Generated by Django 3.2.15 on 2022-10-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookExchange', '0003_auto_20221021_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooks',
            name='author',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='condition',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
