# Generated by Django 4.1.2 on 2022-10-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BookExchange", "0003_textbooks_price"),
        ("BookExchange", "0004_auto_20221021_1819"),
    ]

    operations = []
