# Generated by Django 4.1.2 on 2022-10-22 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookExchange", "0005_merge_0003_textbooks_price_0004_auto_20221021_1819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbooks",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
