# Generated by Django 4.1.2 on 2022-10-22 04:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookExchange", "0006_alter_textbooks_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbooks",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal(
                            "0.05000000000000000277555756156289135105907917022705078125"
                        )
                    )
                ],
            ),
        ),
    ]
