# Generated by Django 4.1.2 on 2022-10-22 04:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookExchange", "0007_alter_textbooks_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbooks",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
